# Generated by Django 4.1.1 on 2022-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceDB',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('pension_lottery_1000', models.IntegerField()),
                ('pension_lottery_5000', models.IntegerField()),
                ('instant_lottery_1000', models.IntegerField()),
                ('instant_lottery_2000', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('daily_sales', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
