# Generated by Django 4.1.1 on 2022-11-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceDB',
            new_name='POSDB',
        ),
    ]
