# Generated by Django 4.1.1 on 2022-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0003_alter_posdb_balance_alter_posdb_daily_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdb',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
