# Generated by Django 4.1.1 on 2022-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0005_alter_posdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdb',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
