# Generated by Django 4.1.1 on 2022-11-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0006_alter_posdb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdb',
            name='date',
        ),
    ]
