# Generated by Django 4.1.1 on 2022-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0008_posdb_sale_time_alter_posdb_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posdb',
            old_name='daily_sales',
            new_name='pay',
        ),
        migrations.AddField(
            model_name='posdb',
            name='sale',
            field=models.IntegerField(null=True),
        ),
    ]
