# Generated by Django 4.1.1 on 2022-11-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0009_rename_daily_sales_posdb_pay_posdb_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdb',
            name='daily_sale_start',
            field=models.DateTimeField(null=True),
        ),
    ]
