# Generated by Django 4.1.1 on 2022-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0010_posdb_daily_sale_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdb',
            name='base_balance',
            field=models.DateTimeField(null=True),
        ),
    ]
