# Generated by Django 4.1.1 on 2022-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0011_posdb_base_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdb',
            name='base_balance',
            field=models.IntegerField(null=True),
        ),
    ]
