# Generated by Django 4.1.1 on 2022-11-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0012_alter_posdb_base_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdb',
            name='balance',
        ),
    ]
