# Generated by Django 4.1.1 on 2022-11-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0014_posdb_ismodify'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdb',
            name='instant_lottery_1000_Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posdb',
            name='instant_lottery_2000_Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posdb',
            name='pension_lottery_1000_Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posdb',
            name='pension_lottery_5000_Qty',
            field=models.IntegerField(null=True),
        ),
    ]
