# Generated by Django 4.1.1 on 2022-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSApp', '0015_posdb_instant_lottery_1000_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdb',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
